### ISSUE TITLE
Crashing when trying to change songs

### ISSUE THREAD

**Issue by ffidan61** [wildeyedskies/stmp#10]
Thanks for this project, yesterday I was searching for a terminal client for navidrome but couldn't find one and today I saw the post on r/selfhosted :)

I can start a song but as I want to go change the song stmp crashes. 
It reports a runtime error: index out of range [0] with length main.handleMpvEvents(0xc0004e2180) created by main.InitGui

Hope this helped happy to give more infos :+1:

**Comment by wildeyedskies** [comment]
Can you tell me the exact flow you're following? Are you adding songs via `Enter` to immediately play them or `a` to add to the queue. When changing songs are you deleting from the queue with `d` or `D` or something else?

**Comment by wildeyedskies** [comment]
Reproduced, this looks like it's a race condition caused by my lazy event handling logic. Fix requires a bit of refactoring so I'll try to work on it over the weekend.
