### ISSUE TITLE
crash on startup: signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76e22a]

### ISSUE THREAD

**Issue by mschaaf** [wildeyedskies/stmp#14]
I compiled stmp with go version go1.16.2 linux/amd64
added a configuration under `~/.config/stmp/stmp.toml`
but stmp crashes on startup with
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76e22a]

goroutine 1 [running]:
main.main()
        <path>/stmp/stmp.go:42 +0x16a
```

Is there a way to find the reason for the crash?

**Comment by mschaaf** [comment]
Ok the error seems to happen when the GetIndexes returns null and in my case, it does it because the server certificate is invalid.
`x509: certificate has expired or is not yet valid ...`

**Comment by mschaaf** [comment]
Configuring stmp to ignore invalid certs with `http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}` fixed the issue for me.

**Comment by wildeyedskies** [comment]
Please use a valid certificate. Accepting invalid certs is a security risk and a bad practice in general. You can get a valid cert at https://certbot.eff.org/
