### ISSUE TITLE
 fatal error: 'mpv/client.h' file not found

### ISSUE THREAD

**Issue by xinmans** [wildeyedskies/stmp#20]
xinmans@LincM1 stmp % go build .
# golang.org/x/sys/unix
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../go/pkg/mod/golang.org/x/sys@v0.0.0-20201017003518-b09fb700fbb7/unix/zsyscall_darwin_arm64.go:121:3: too many errors
# github.com/yourok/go-mpv/mpv
../go/pkg/mod/github.com/yourok/go-mpv@v0.0.0-20160721123233-ecdfd901e332/mpv/consts.go:3:10: fatal error: 'mpv/client.h' file not found
#include <mpv/client.h>
         ^~~~~~~~~~~~~~
1 error generated.
xinmans@LincM1 stmp %

**Comment by wildeyedskies** [comment]
What operating system is this happening under. You likely need to install the `mpv` development libraries. On ubuntu I think that's mpv-dev or libmpv-dev

**Comment by dweymouth** [comment]
You may find the Mac build instructions for my Subsonic client that also is Go-based and uses libmpv helpful.  https://github.com/dweymouth/supersonic

**Comment by wildeyedskies** [comment]
Added OSX instructions to readme. Thanks @dweymouth!
