### ISSUE TITLE
No songs show up in playlists

### ISSUE THREAD

**Issue by Virtuo1** [wildeyedskies/stmp#21]
It seems like `Entries` in `SubsonicPlaylist` does not get populated with songs when calling `GetPlaylists`.
I feel like I am missing something as to how playlist songs are fetched, considering no songs are fetched in this [example](http://www.subsonic.org/pages/inc/api/examples/playlists_example_1.xml) on getPlaylists from the subsonic api docs.

One solution would be using GetPlaylist to fetch the songs in each playlist and put them into respective playlist. This works, but I'm not sure how it even works to begin with due to reasons stated above.

Anyhow, I'd be happy to help.

**Comment by Virtuo1** [comment]
I just tried connecting to an actual subsonic server, and the problem persists. This is not a navidrome issue.

**Comment by xxxserxxx** [comment]
Is this still open? The PR looks like it was merged -- at least, the changes look like they're in the current code base.

**Comment by Virtuo1** [comment]
Wasn't merged but the issue seems to be resolved with recent changes anyways. Closing..
